name = "savofinance"
compatibility_date = "2026-06-04"
compatibility_flags = [ "nodejs_compat" ]

[vars]
PUBLIC_SUPABASE_URL = "https://xhlbdjpdmzcyyyuehlql.supabase.co"
PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_knKW83Pt7_CuNn-WQ1vQQA_7JFqLja8"